name: Build ARM Binary

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        go-version: [1.19]
        platform: [linux/arm64]

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}

    - name: Build binary
      run: |
        GOOS=linux GOARCH=arm64 go build -o output/mmdb2csv

    - name: Upload binary
      uses: actions/upload-artifact@v2
      with:
        name: mmdb2csv-arm64
        path: output/mmdb2cs
