name: Build ARM Binary

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:  # 允许手动触发

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        go-version: [1.21]  # 更新到更新的Go版本
        arch: [arm64, arm]
        include:
          - arch: arm
            goarch: arm
            goarm: 7
          - arch: arm64
            goarch: arm64

    steps:
    - name: Checkout code
      uses: actions/checkout@v4  # 使用最新版本

    - name: Set up Go
      uses: actions/setup-go@v5  # 使用最新版本
      with:
        go-version: ${{ matrix.go-version }}

    - name: Build binary
      run: |
        mkdir -p output
        GOOS=linux GOARCH=${{ matrix.goarch }} ${{ matrix.arch == 'arm' && format('GOARM={0}', matrix.goarm) || '' }} go build -o output/mmdb2csv-${{ matrix.arch }}

    - name: Upload binary
      uses: actions/upload-artifact@v4  # 更新到v4版本
      with:
        name: mmdb2csv-${{ matrix.arch }}
        path: output/mmdb2csv-${{ matrix.arch }}
        retention-days: 7
